/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Class.Customer;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Arun
 */
public class CustomerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form CustomerDashboard
     */
    public CustomerDashboard() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        panelSeatSelection.setVisible(false);
        jPanel1.setVisible(false);
        lblUsername.setText(Customer.customerName);
    }

    int seatRequired;
    int seatSelected = 0;
    int[] x = new int[41];
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        panelSeatSelection = new javax.swing.JLayeredPane();
        btn37 = new javax.swing.JButton();
        btn38 = new javax.swing.JButton();
        btn39 = new javax.swing.JButton();
        btn40 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn34 = new javax.swing.JButton();
        btn35 = new javax.swing.JButton();
        btn36 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        btn29 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn27 = new javax.swing.JButton();
        btn28 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        click = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N

        lblUsername.setFont(new java.awt.Font("Roboto Light", 1, 20)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(129, 132, 135));
        lblUsername.setText("USERNAME");

        btnLogout.setBackground(new java.awt.Color(129, 132, 135));
        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 819, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 100));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 33, 56), 2));
        jPanel4.setEnabled(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 33, 56), 2));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 40, 1));
        jSpinner1.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinner1, ""));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel5.setText("NO OF SEATS NEEDED");
        jLabel5.setToolTipText("");

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpinner1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 420, 450));

        panelSeatSelection.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(190, 33, 56), 2, true));
        panelSeatSelection.setEnabled(false);
        panelSeatSelection.setOpaque(true);
        panelSeatSelection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn37.setBackground(new java.awt.Color(255, 255, 255));
        btn37.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn37.setText("37");
        btn37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn37MouseClicked(evt);
            }
        });
        btn37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn37ActionPerformed(evt);
            }
        });
        panelSeatSelection.add(btn37, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, 60, 50));

        btn38.setBackground(new java.awt.Color(255, 255, 255));
        btn38.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn38.setText("38");
        btn38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn38MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn38, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 250, 60, 50));

        btn39.setBackground(new java.awt.Color(255, 255, 255));
        btn39.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn39.setText("39");
        btn39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn39MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn39, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 60, 50));

        btn40.setBackground(new java.awt.Color(255, 255, 255));
        btn40.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn40.setText("40");
        btn40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn40MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn40, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 60, 50));

        btn33.setBackground(new java.awt.Color(255, 255, 255));
        btn33.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn33.setText("33");
        btn33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn33MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn33, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 60, 50));

        btn34.setBackground(new java.awt.Color(255, 255, 255));
        btn34.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn34.setText("34");
        btn34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn34MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn34, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 60, 50));

        btn35.setBackground(new java.awt.Color(255, 255, 255));
        btn35.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn35.setText("35");
        btn35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn35MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn35, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 60, 50));

        btn36.setBackground(new java.awt.Color(255, 255, 255));
        btn36.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn36.setText("36");
        btn36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn36MouseClicked(evt);
            }
        });
        btn36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn36ActionPerformed(evt);
            }
        });
        panelSeatSelection.add(btn36, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 60, 50));

        btn30.setBackground(new java.awt.Color(255, 255, 255));
        btn30.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn30.setText("30");
        btn30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn30MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn30, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 60, 50));

        btn29.setBackground(new java.awt.Color(255, 255, 255));
        btn29.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn29.setText("29");
        btn29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn29MouseClicked(evt);
            }
        });
        btn29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn29ActionPerformed(evt);
            }
        });
        panelSeatSelection.add(btn29, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 60, 50));

        btn31.setBackground(new java.awt.Color(255, 255, 255));
        btn31.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn31.setText("31");
        btn31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn31MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn31, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 60, 50));

        btn32.setBackground(new java.awt.Color(255, 255, 255));
        btn32.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn32.setText("32");
        btn32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn32MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn32, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 60, 50));

        btn25.setBackground(new java.awt.Color(255, 255, 255));
        btn25.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn25.setText("25");
        btn25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn25MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn25MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn25MousePressed(evt);
            }
        });
        panelSeatSelection.add(btn25, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 60, 50));

        btn26.setBackground(new java.awt.Color(255, 255, 255));
        btn26.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn26.setText("26");
        btn26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn26MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn26, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 60, 50));

        btn27.setBackground(new java.awt.Color(255, 255, 255));
        btn27.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn27.setText("27");
        btn27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn27MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn27, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 60, 50));

        btn28.setBackground(new java.awt.Color(255, 255, 255));
        btn28.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn28.setText("28");
        btn28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn28MouseClicked(evt);
            }
        });
        btn28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn28ActionPerformed(evt);
            }
        });
        panelSeatSelection.add(btn28, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 60, 50));

        btn23.setBackground(new java.awt.Color(255, 255, 255));
        btn23.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn23.setText("23");
        btn23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn23MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 60, 50));

        btn22.setBackground(new java.awt.Color(255, 255, 255));
        btn22.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn22.setText("22");
        btn22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn22MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 60, 50));

        btn21.setBackground(new java.awt.Color(255, 255, 255));
        btn21.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn21.setText("21");
        btn21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn21MouseClicked(evt);
            }
        });
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });
        panelSeatSelection.add(btn21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 60, 50));

        btn17.setBackground(new java.awt.Color(255, 255, 255));
        btn17.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn17.setText("17");
        btn17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn17MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn17MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn17MousePressed(evt);
            }
        });
        panelSeatSelection.add(btn17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 60, 50));

        btn18.setBackground(new java.awt.Color(255, 255, 255));
        btn18.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn18.setText("18");
        btn18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn18MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 60, 50));

        btn19.setBackground(new java.awt.Color(255, 255, 255));
        btn19.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn19.setText("19");
        btn19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn19MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 60, 50));

        btn20.setBackground(new java.awt.Color(255, 255, 255));
        btn20.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn20.setText("20");
        btn20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn20MouseClicked(evt);
            }
        });
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        panelSeatSelection.add(btn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 60, 50));

        btn24.setBackground(new java.awt.Color(255, 255, 255));
        btn24.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn24.setText("24");
        btn24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn24MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn24, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 60, 50));

        btn14.setBackground(new java.awt.Color(255, 255, 255));
        btn14.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn14.setText("14");
        btn14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn14MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 60, 50));

        btn13.setBackground(new java.awt.Color(255, 255, 255));
        btn13.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn13.setText("13");
        btn13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn13MouseClicked(evt);
            }
        });
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });
        panelSeatSelection.add(btn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 60, 50));

        btn15.setBackground(new java.awt.Color(255, 255, 255));
        btn15.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn15.setText("15");
        btn15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn15MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 60, 50));

        btn16.setBackground(new java.awt.Color(255, 255, 255));
        btn16.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn16.setText("16");
        btn16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn16MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 60, 50));

        btn9.setBackground(new java.awt.Color(255, 255, 255));
        btn9.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn9.setText("09");
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn9MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn9MousePressed(evt);
            }
        });
        panelSeatSelection.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 60, 50));

        btn10.setBackground(new java.awt.Color(255, 255, 255));
        btn10.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn10.setText("10");
        btn10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn10MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 60, 50));

        btn11.setBackground(new java.awt.Color(255, 255, 255));
        btn11.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn11.setText("11");
        btn11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn11MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 60, 50));

        btn12.setBackground(new java.awt.Color(255, 255, 255));
        btn12.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn12.setText("12");
        btn12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn12MouseClicked(evt);
            }
        });
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        panelSeatSelection.add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 60, 50));

        btn7.setBackground(new java.awt.Color(255, 255, 255));
        btn7.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn7.setText("07");
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn7MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 60, 50));

        btn6.setBackground(new java.awt.Color(255, 255, 255));
        btn6.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn6.setText("06");
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 60, 50));

        btn8.setBackground(new java.awt.Color(255, 255, 255));
        btn8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn8.setText("08");
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
        });
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        panelSeatSelection.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 60, 50));

        btn1.setBackground(new java.awt.Color(255, 255, 255));
        btn1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn1.setText("01");
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn1MousePressed(evt);
            }
        });
        panelSeatSelection.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 60, 50));

        btn2.setBackground(new java.awt.Color(255, 255, 255));
        btn2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn2.setText("02");
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 60, 50));

        btn3.setBackground(new java.awt.Color(255, 255, 255));
        btn3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn3.setText("03");
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 60, 50));

        btn4.setBackground(new java.awt.Color(255, 255, 255));
        btn4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn4.setText("04");
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        panelSeatSelection.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 60, 50));

        btn5.setBackground(new java.awt.Color(255, 255, 255));
        btn5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btn5.setText("05");
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });
        panelSeatSelection.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 60, 50));
        panelSeatSelection.add(click, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 80, 30));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SEAT");
        panelSeatSelection.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 50, 50));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DRIVER");
        panelSeatSelection.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 50, 50));

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REFRESH");
        panelSeatSelection.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 100, 30));

        jButton2.setBackground(new java.awt.Color(190, 33, 56));
        jButton2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CLOSE");
        panelSeatSelection.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, 100, 30));

        jButton3.setBackground(new java.awt.Color(0, 153, 51));
        jButton3.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("NEXT");
        panelSeatSelection.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 100, 30));

        jPanel4.add(panelSeatSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 950, 460));

        panelTable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 33, 56), 2));
        jTable1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setDragEnabled(true);
        jTable1.setEnabled(false);
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(190, 33, 56));
        jTable1.setIntercellSpacing(new java.awt.Dimension(10, 2));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(190, 33, 56));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        panelTable.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 936, 480));

        jPanel4.add(panelTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 950, 490));

        btn.setText("jButton3");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        jPanel4.add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 1000, 620));

        jPanel3.setBackground(new java.awt.Color(190, 33, 56));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 300, 160));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 300, 160));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 300, 160));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 360, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        panelTable.setVisible(false);
        panelSeatSelection.setVisible(false);
    }//GEN-LAST:event_btnActionPerformed

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        seatSelection(1);
    }//GEN-LAST:event_btn1MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        seatSelection(2);
    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        seatSelection(3);
    }//GEN-LAST:event_btn3MouseClicked

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
        seatSelection(4);
    }//GEN-LAST:event_btn4MouseClicked

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        seatSelection(5);
    }//GEN-LAST:event_btn5MouseClicked

    private void btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseEntered
    }//GEN-LAST:event_btn1MouseEntered

    private void btn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MousePressed
    }//GEN-LAST:event_btn1MousePressed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseClicked
        // TODO add your handling code here:
        seatSelection(7);
    }//GEN-LAST:event_btn7MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        // TODO add your handling code here:
        seatSelection(6);
    }//GEN-LAST:event_btn6MouseClicked

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        // TODO add your handling code here:
        seatSelection(8);
    }//GEN-LAST:event_btn8MouseClicked

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn14MouseClicked
        // TODO add your handling code here:
        seatSelection(14);
    }//GEN-LAST:event_btn14MouseClicked

    private void btn13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn13MouseClicked
        // TODO add your handling code here:
        seatSelection(13);
    }//GEN-LAST:event_btn13MouseClicked

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn15MouseClicked
        // TODO add your handling code here:
        seatSelection(15);
    }//GEN-LAST:event_btn15MouseClicked

    private void btn16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn16MouseClicked
        // TODO add your handling code here:
        seatSelection(16);
    }//GEN-LAST:event_btn16MouseClicked

    private void btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseClicked
        // TODO add your handling code here:
        seatSelection(9);
    }//GEN-LAST:event_btn9MouseClicked

    private void btn9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9MouseEntered

    private void btn9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9MousePressed

    private void btn10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10MouseClicked
        // TODO add your handling code here:
        seatSelection(10);
    }//GEN-LAST:event_btn10MouseClicked

    private void btn11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn11MouseClicked
        // TODO add your handling code here:
        seatSelection(11);
    }//GEN-LAST:event_btn11MouseClicked

    private void btn12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn12MouseClicked
        // TODO add your handling code here:
        seatSelection(12);
    }//GEN-LAST:event_btn12MouseClicked

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn30MouseClicked
        // TODO add your handling code here:
        seatSelection(30);
    }//GEN-LAST:event_btn30MouseClicked

    private void btn29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn29MouseClicked
        // TODO add your handling code here:
        seatSelection(29);
    }//GEN-LAST:event_btn29MouseClicked

    private void btn29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn29ActionPerformed

    private void btn31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn31MouseClicked
        // TODO add your handling code here:
        seatSelection(31);
    }//GEN-LAST:event_btn31MouseClicked

    private void btn32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn32MouseClicked
        // TODO add your handling code here:
        seatSelection(32);
    }//GEN-LAST:event_btn32MouseClicked

    private void btn25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn25MouseClicked
        // TODO add your handling code here:
        seatSelection(25);
    }//GEN-LAST:event_btn25MouseClicked

    private void btn25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn25MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn25MouseEntered

    private void btn25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn25MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn25MousePressed

    private void btn26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn26MouseClicked
        // TODO add your handling code here:
        seatSelection(26);
    }//GEN-LAST:event_btn26MouseClicked

    private void btn27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn27MouseClicked
        // TODO add your handling code here:
        seatSelection(27);
    }//GEN-LAST:event_btn27MouseClicked

    private void btn28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn28MouseClicked
        // TODO add your handling code here:
        seatSelection(28);
    }//GEN-LAST:event_btn28MouseClicked

    private void btn28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn28ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn28ActionPerformed

    private void btn23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn23MouseClicked
        // TODO add your handling code here:
        seatSelection(23);
    }//GEN-LAST:event_btn23MouseClicked

    private void btn22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn22MouseClicked
        // TODO add your handling code here:
        seatSelection(22);
    }//GEN-LAST:event_btn22MouseClicked

    private void btn21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn21MouseClicked
        // TODO add your handling code here:
        seatSelection(21);
    }//GEN-LAST:event_btn21MouseClicked

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn17MouseClicked
        // TODO add your handling code here:
        seatSelection(17);
    }//GEN-LAST:event_btn17MouseClicked

    private void btn17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn17MouseEntered

    private void btn17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn17MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn17MousePressed

    private void btn18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn18MouseClicked
        // TODO add your handling code here:
        seatSelection(18);
    }//GEN-LAST:event_btn18MouseClicked

    private void btn19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn19MouseClicked
        // TODO add your handling code here:
        seatSelection(19);
    }//GEN-LAST:event_btn19MouseClicked

    private void btn20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn20MouseClicked
        // TODO add your handling code here:
        seatSelection(20);
    }//GEN-LAST:event_btn20MouseClicked

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn24MouseClicked
        // TODO add your handling code here:
        seatSelection(24);
    }//GEN-LAST:event_btn24MouseClicked

    private void btn33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn33MouseClicked
        // TODO add your handling code here:
        seatSelection(33);
    }//GEN-LAST:event_btn33MouseClicked

    private void btn34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn34MouseClicked
        // TODO add your handling code here:
        seatSelection(34);
    }//GEN-LAST:event_btn34MouseClicked

    private void btn35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn35MouseClicked
        // TODO add your handling code here:
        seatSelection(35);
    }//GEN-LAST:event_btn35MouseClicked

    private void btn36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn36MouseClicked
        // TODO add your handling code here:
        seatSelection(36);
    }//GEN-LAST:event_btn36MouseClicked

    private void btn36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn36ActionPerformed

    private void btn37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn37MouseClicked
        // TODO add your handling code here:
        seatSelection(37);
    }//GEN-LAST:event_btn37MouseClicked

    private void btn37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn37ActionPerformed

    private void btn38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn38MouseClicked
        // TODO add your handling code here:
        seatSelection(38);
    }//GEN-LAST:event_btn38MouseClicked

    private void btn39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn39MouseClicked
        // TODO add your handling code here:
        seatSelection(39);
    }//GEN-LAST:event_btn39MouseClicked

    private void btn40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn40MouseClicked
        // TODO add your handling code here:
        seatSelection(40);
    }//GEN-LAST:event_btn40MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        seatRequired=(int)jSpinner1.getValue();
        panelTable.setVisible(false);
        panelSeatSelection.setVisible(true);
        jPanel1.setVisible(false);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn27;
    private javax.swing.JButton btn28;
    private javax.swing.JButton btn29;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JButton btn34;
    private javax.swing.JButton btn35;
    private javax.swing.JButton btn36;
    private javax.swing.JButton btn37;
    private javax.swing.JButton btn38;
    private javax.swing.JButton btn39;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn40;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel click;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLayeredPane panelSeatSelection;
    private javax.swing.JPanel panelTable;
    // End of variables declaration//GEN-END:variables

    private void checkValueReached()
    {
        if(seatSelected==seatRequired)
        {
            if((x[1]%2)!=0)
                btn1.setEnabled(true);
            else
                btn1.setEnabled(false);
            
            if((x[2]%2)!=0)
                btn2.setEnabled(true);
            else
                btn2.setEnabled(false);
            
            if((x[3]%2)!=0)
                btn3.setEnabled(true);
            else
                btn3.setEnabled(false);
            
            if((x[4]%2)!=0)
                btn4.setEnabled(true);
            else
                btn4.setEnabled(false);
           
            if((x[5]%2)!=0)
                btn5.setEnabled(true);
            else
                btn5.setEnabled(false);
            
            if((x[6]%2)!=0)
                btn6.setEnabled(true);
            else
                btn6.setEnabled(false);
            
            if((x[7]%2)!=0)
                btn7.setEnabled(true);
            else
                btn7.setEnabled(false);
            
            if((x[8]%2)!=0)
                btn8.setEnabled(true);
            else
                btn8.setEnabled(false);
            
            if((x[9]%2)!=0)
                btn9.setEnabled(true);
            else
                btn9.setEnabled(false);
           
            if((x[10]%2)!=0)
                btn10.setEnabled(true);
            else
                btn10.setEnabled(false);
            
            if((x[11]%2)!=0)
                btn11.setEnabled(true);
            else
                btn11.setEnabled(false);
            
            if((x[12]%2)!=0)
                btn12.setEnabled(true);
            else
                btn12.setEnabled(false);
            
            if((x[13]%2)!=0)
                btn13.setEnabled(true);
            else
                btn13.setEnabled(false);
            
            if((x[14]%2)!=0)
                btn14.setEnabled(true);
            else
                btn14.setEnabled(false);
           
            if((x[15]%2)!=0)
                btn15.setEnabled(true);
            else
                btn15.setEnabled(false);
            
            if((x[16]%2)!=0)
                btn16.setEnabled(true);
            else
                btn16.setEnabled(false);
            
            if((x[17]%2)!=0)
                btn17.setEnabled(true);
            else
                btn17.setEnabled(false);
            
            if((x[18]%2)!=0)
                btn18.setEnabled(true);
            else
                btn18.setEnabled(false);
            
            if((x[19]%2)!=0)
                btn19.setEnabled(true);
            else
                btn19.setEnabled(false);
           
            if((x[20]%2)!=0)
                btn20.setEnabled(true);
            else
                btn20.setEnabled(false);
            
            if((x[21]%2)!=0)
                btn21.setEnabled(true);
            else
                btn21.setEnabled(false);
            
            if((x[22]%2)!=0)
                btn22.setEnabled(true);
            else
                btn22.setEnabled(false);
            
            if((x[23]%2)!=0)
                btn23.setEnabled(true);
            else
                btn23.setEnabled(false);
            
            if((x[24]%2)!=0)
                btn24.setEnabled(true);
            else
                btn24.setEnabled(false);
           
            if((x[25]%2)!=0)
                btn25.setEnabled(true);
            else
                btn25.setEnabled(false);
            
            if((x[26]%2)!=0)
                btn26.setEnabled(true);
            else
                btn26.setEnabled(false);
            
            if((x[27]%2)!=0)
                btn27.setEnabled(true);
            else
                btn27.setEnabled(false);
            
            if((x[28]%2)!=0)
                btn28.setEnabled(true);
            else
                btn28.setEnabled(false);
            
            if((x[29]%2)!=0)
                btn29.setEnabled(true);
            else
                btn29.setEnabled(false);
           
            if((x[30]%2)!=0)
                btn30.setEnabled(true);
            else
                btn30.setEnabled(false);
            
            if((x[31]%2)!=0)
                btn31.setEnabled(true);
            else
                btn31.setEnabled(false);
            
            if((x[32]%2)!=0)
                btn32.setEnabled(true);
            else
                btn32.setEnabled(false);
            
            if((x[33]%2)!=0)
                btn33.setEnabled(true);
            else
                btn33.setEnabled(false);
            
            if((x[34]%2)!=0)
                btn34.setEnabled(true);
            else
                btn34.setEnabled(false);
           
            if((x[35]%2)!=0)
                btn35.setEnabled(true);
            else
                btn35.setEnabled(false);
            
            if((x[36]%2)!=0)
                btn36.setEnabled(true);
            else
                btn36.setEnabled(false);
            
            if((x[37]%2)!=0)
                btn37.setEnabled(true);
            else
                btn37.setEnabled(false);
            
            if((x[38]%2)!=0)
                btn38.setEnabled(true);
            else
                btn38.setEnabled(false);
            
            if((x[39]%2)!=0)
                btn39.setEnabled(true);
            else
                btn39.setEnabled(false);
           
            if((x[40]%2)!=0)
                btn40.setEnabled(true);
            else
                btn40.setEnabled(false);
        }
        else
        {
            enableAllSeats();
        }
    }
    
    private void seatSelection(int index)
    {
        if((seatSelected<seatRequired)||((x[index]%2)==1))
        {
            x[index]++;
            if((x[index]%2)==0)
            { 
                switch(index)
                {
                    case 1:
                        btn1.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 2:
                        btn2.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 3:
                        btn3.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 4:
                        btn4.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 5:
                        btn5.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 6:
                        btn6.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 7:
                        btn7.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 8:
                        btn8.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 9:
                        btn9.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 10:
                        btn10.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 11:
                        btn11.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 12:
                        btn12.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 13:
                        btn13.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 14:
                        btn14.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 15:
                        btn15.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 16:
                        btn16.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 17:
                        btn17.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 18:
                        btn18.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 19:
                        btn19.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 20:
                        btn20.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 21:
                        btn21.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 22:
                        btn22.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 23:
                        btn23.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 24:
                        btn24.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 25:
                        btn25.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 26:
                        btn26.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 27:
                        btn27.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 28:
                        btn28.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 29:
                        btn29.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 30:
                        btn30.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 31:
                        btn31.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 32:
                        btn32.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 33:
                        btn33.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 34:
                        btn34.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 35:
                        btn35.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 36:
                        btn36.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 37:
                        btn37.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 38:
                        btn38.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 39:
                        btn39.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                    case 40:
                        btn40.setBackground(new java.awt.Color(255, 255, 255));
                        break;
                }
                seatSelected--;
            }
            else
            {
                switch(index)
                {
                    case 1:
                        btn1.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 2:
                        btn2.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 3:
                        btn3.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 4:
                        btn4.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 5:
                        btn5.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 6:
                        btn6.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 7:
                        btn7.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 8:
                        btn8.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 9:
                        btn9.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 10:
                        btn10.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 11:
                        btn11.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 12:
                        btn12.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 13:
                        btn13.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 14:
                        btn14.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 15:
                        btn15.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 16:
                        btn16.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 17:
                        btn17.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 18:
                        btn18.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 19:
                        btn19.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 20:
                        btn20.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 21:
                        btn21.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 22:
                        btn22.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 23:
                        btn23.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 24:
                        btn24.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 25:
                        btn25.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 26:
                        btn26.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 27:
                        btn27.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 28:
                        btn28.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 29:
                        btn29.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 30:
                        btn30.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 31:
                        btn31.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 32:
                        btn32.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 33:
                        btn33.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 34:
                        btn34.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 35:
                        btn35.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 36:
                        btn36.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 37:
                        btn37.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 38:
                        btn38.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 39:
                        btn39.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                    case 40:
                        btn40.setBackground(new java.awt.Color(102, 204, 0));
                        break;
                }
                seatSelected++;
            }
            click.setText(""+seatSelected);
            checkValueReached();
        }
        else
        { 
            JOptionPane.showMessageDialog(rootPane,"Sorry cannot select more seats,"
                    + " than you requested" , "Error", JOptionPane.ERROR_MESSAGE);
        }
    }   

    private void enableAllSeats() {
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        btn3.setEnabled(true);
        btn4.setEnabled(true);
        btn5.setEnabled(true);
        btn6.setEnabled(true);
        btn7.setEnabled(true);
        btn8.setEnabled(true);
        btn9.setEnabled(true);
        btn10.setEnabled(true);
        btn11.setEnabled(true);
        btn12.setEnabled(true);
        btn13.setEnabled(true);
        btn14.setEnabled(true);
        btn15.setEnabled(true);
        btn16.setEnabled(true);
        btn17.setEnabled(true);
        btn18.setEnabled(true);
        btn19.setEnabled(true);
        btn20.setEnabled(true);
        btn21.setEnabled(true);
        btn22.setEnabled(true);
        btn23.setEnabled(true);
        btn24.setEnabled(true);
        btn25.setEnabled(true);
        btn26.setEnabled(true);
        btn27.setEnabled(true);
        btn28.setEnabled(true);
        btn29.setEnabled(true);
        btn30.setEnabled(true);
        btn31.setEnabled(true);
        btn32.setEnabled(true);
        btn33.setEnabled(true);
        btn34.setEnabled(true);
        btn35.setEnabled(true);
        btn36.setEnabled(true);
        btn37.setEnabled(true);
        btn38.setEnabled(true);
        btn39.setEnabled(true);
        btn40.setEnabled(true);
    }
}
