/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Class.Customer;
import java.awt.Color;
import java.awt.Toolkit;
import java.time.Instant;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author Arun
 */
public class CustomerRegisterFrame extends javax.swing.JFrame {


    /**
     * Creates new form CustomerRegisterPage
     */
    public CustomerRegisterFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        hideOutterLabel();
        dateDOB.setMaxSelectableDate(Date.from(Instant.now()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblInFName = new javax.swing.JLabel();
        lblOutCity = new javax.swing.JLabel();
        lblOutPhoneNumber1 = new javax.swing.JLabel();
        lblInCity = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lblOutFName = new javax.swing.JLabel();
        lblInSName = new javax.swing.JLabel();
        lblOutDOB = new javax.swing.JLabel();
        lblOutSName = new javax.swing.JLabel();
        lblInPhoneNumber = new javax.swing.JLabel();
        lblInStreetName = new javax.swing.JLabel();
        lblOutStreetName = new javax.swing.JLabel();
        lblOutPhoneNumber = new javax.swing.JLabel();
        lblOutConPassword = new javax.swing.JLabel();
        lblInConPassword = new javax.swing.JLabel();
        panelPassword = new javax.swing.JPanel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        lblInDOB = new javax.swing.JLabel();
        lblOutEmail = new javax.swing.JLabel();
        lblInEmail = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        lblInPassword = new javax.swing.JLabel();
        lblOutPassword = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        dateDOB = new com.toedter.calendar.JDateChooser();
        txtPhoneNumber = new javax.swing.JTextField();
        txtStreet = new javax.swing.JTextField();
        txtSurName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        lblStrong = new javax.swing.JLabel();
        lblWeak = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        lbl1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 33, 56)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(190, 33, 56));
        jLabel5.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CUSTOMER-  REGISTER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 660, 50));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(129, 132, 135));
        jLabel3.setText("Already registered, Login here");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 330, -1));

        btnLogin.setBackground(new java.awt.Color(129, 132, 135));
        btnLogin.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN HERE");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 190, -1));

        btnHome.setBackground(new java.awt.Color(0, 153, 102));
        btnHome.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 140, -1));

        jPanel2.setBackground(new java.awt.Color(190, 33, 56));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 50));

        lblInFName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblInFName.setForeground(new java.awt.Color(118, 117, 118));
        lblInFName.setText("FIRST NAME");
        jPanel1.add(lblInFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        lblOutCity.setBackground(new java.awt.Color(255, 255, 255));
        lblOutCity.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblOutCity.setForeground(new java.awt.Color(190, 33, 56));
        lblOutCity.setText("  CITY  ");
        lblOutCity.setToolTipText("");
        lblOutCity.setOpaque(true);
        jPanel1.add(lblOutCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        lblOutPhoneNumber1.setBackground(new java.awt.Color(255, 255, 255));
        lblOutPhoneNumber1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblOutPhoneNumber1.setForeground(new java.awt.Color(190, 33, 56));
        lblOutPhoneNumber1.setText("GENDER");
        lblOutPhoneNumber1.setToolTipText("");
        lblOutPhoneNumber1.setOpaque(true);
        jPanel1.add(lblOutPhoneNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        lblInCity.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblInCity.setForeground(new java.awt.Color(118, 117, 118));
        lblInCity.setText("CITY  ");
        jPanel1.add(lblInCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        lbl5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbl5.setForeground(new java.awt.Color(118, 117, 118));
        lbl5.setText("*Email will be used as username");
        jPanel1.add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 310, -1));

        lblOutFName.setBackground(new java.awt.Color(255, 255, 255));
        lblOutFName.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblOutFName.setForeground(new java.awt.Color(190, 33, 56));
        lblOutFName.setText("  FIRST NAME  ");
        lblOutFName.setToolTipText("");
        lblOutFName.setOpaque(true);
        jPanel1.add(lblOutFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        lblInSName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblInSName.setForeground(new java.awt.Color(118, 117, 118));
        lblInSName.setText("SURNAME NAME  ");
        jPanel1.add(lblInSName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        lblOutDOB.setBackground(new java.awt.Color(255, 255, 255));
        lblOutDOB.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblOutDOB.setForeground(new java.awt.Color(190, 33, 56));
        lblOutDOB.setText("  DATE OF BIRTH  ");
        lblOutDOB.setToolTipText("");
        lblOutDOB.setOpaque(true);
        jPanel1.add(lblOutDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        lblOutSName.setBackground(new java.awt.Color(255, 255, 255));
        lblOutSName.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblOutSName.setForeground(new java.awt.Color(190, 33, 56));
        lblOutSName.setText("  SURNAME NAME  ");
        lblOutSName.setToolTipText("");
        lblOutSName.setOpaque(true);
        jPanel1.add(lblOutSName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        lblInPhoneNumber.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblInPhoneNumber.setForeground(new java.awt.Color(118, 117, 118));
        lblInPhoneNumber.setText("PHONE NUMBER  ");
        jPanel1.add(lblInPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        lblInStreetName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblInStreetName.setForeground(new java.awt.Color(118, 117, 118));
        lblInStreetName.setText("STREET NAME  ");
        jPanel1.add(lblInStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        lblOutStreetName.setBackground(new java.awt.Color(255, 255, 255));
        lblOutStreetName.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblOutStreetName.setForeground(new java.awt.Color(190, 33, 56));
        lblOutStreetName.setText("  STREET NAME  ");
        lblOutStreetName.setToolTipText("");
        lblOutStreetName.setOpaque(true);
        jPanel1.add(lblOutStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        lblOutPhoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        lblOutPhoneNumber.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblOutPhoneNumber.setForeground(new java.awt.Color(190, 33, 56));
        lblOutPhoneNumber.setText("  PHONE NUMBER  ");
        lblOutPhoneNumber.setToolTipText("");
        lblOutPhoneNumber.setOpaque(true);
        jPanel1.add(lblOutPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        lblOutConPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblOutConPassword.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblOutConPassword.setForeground(new java.awt.Color(190, 33, 56));
        lblOutConPassword.setText("  CONFIRM PASSWORD  ");
        lblOutConPassword.setToolTipText("");
        lblOutConPassword.setOpaque(true);
        jPanel1.add(lblOutConPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        lblInConPassword.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblInConPassword.setForeground(new java.awt.Color(118, 117, 118));
        lblInConPassword.setText("CONFIRM PASSWORD  ");
        jPanel1.add(lblInConPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, -1));

        panelPassword.setBackground(new java.awt.Color(255, 255, 255));
        panelPassword.setOpaque(false);
        panelPassword.setPreferredSize(new java.awt.Dimension(330, 50));

        javax.swing.GroupLayout panelPasswordLayout = new javax.swing.GroupLayout(panelPassword);
        panelPassword.setLayout(panelPasswordLayout);
        panelPasswordLayout.setHorizontalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        panelPasswordLayout.setVerticalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(panelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 310, 40));

        txtConfirmPassword.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfirmPasswordKeyReleased(evt);
            }
        });
        jPanel1.add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 310, 40));

        lblInDOB.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblInDOB.setForeground(new java.awt.Color(118, 117, 118));
        lblInDOB.setText("DATE OF BIRTH");
        jPanel1.add(lblInDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        lblOutEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblOutEmail.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblOutEmail.setForeground(new java.awt.Color(190, 33, 56));
        lblOutEmail.setText("  e-MAIL  ");
        lblOutEmail.setToolTipText("");
        lblOutEmail.setOpaque(true);
        jPanel1.add(lblOutEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        lblInEmail.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblInEmail.setForeground(new java.awt.Color(118, 117, 118));
        lblInEmail.setText("e-MAIL");
        jPanel1.add(lblInEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        btnRefresh.setBackground(new java.awt.Color(0, 153, 204));
        btnRefresh.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 140, -1));

        lblInPassword.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblInPassword.setForeground(new java.awt.Color(118, 117, 118));
        lblInPassword.setText("PASSWORD  ");
        jPanel1.add(lblInPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        lblOutPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblOutPassword.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblOutPassword.setForeground(new java.awt.Color(190, 33, 56));
        lblOutPassword.setText("  PASSWORD  ");
        lblOutPassword.setToolTipText("");
        lblOutPassword.setOpaque(true);
        jPanel1.add(lblOutPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        txtCity.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCityKeyReleased(evt);
            }
        });
        jPanel1.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 310, 40));

        txtFirstName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyTyped(evt);
            }
        });
        jPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 310, 40));

        btnSignUp.setBackground(new java.awt.Color(190, 33, 56));
        btnSignUp.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("SIGN UP");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 140, -1));

        txtEmail.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 310, 40));

        dateDOB.setDateFormatString("dd-MMM-yyyy");
        dateDOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateDOBKeyReleased(evt);
            }
        });
        jPanel1.add(dateDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 310, 40));

        txtPhoneNumber.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneNumberKeyReleased(evt);
            }
        });
        jPanel1.add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 310, 40));

        txtStreet.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtStreet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStreetKeyReleased(evt);
            }
        });
        jPanel1.add(txtStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 310, 40));

        txtSurName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtSurName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSurNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtSurName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 310, 40));

        txtPassword.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 310, 40));

        buttonGroup1.add(radioMale);
        radioMale.setSelected(true);
        radioMale.setText("MALE");
        jPanel1.add(radioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        buttonGroup1.add(radioFemale);
        radioFemale.setText("FEMALE");
        radioFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFemaleActionPerformed(evt);
            }
        });
        jPanel1.add(radioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        lblStrong.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblStrong.setForeground(new java.awt.Color(0, 153, 0));
        lblStrong.setText("STRONG");
        lblStrong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(lblStrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 387, -1, 40));

        lblWeak.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblWeak.setForeground(new java.awt.Color(255, 51, 51));
        lblWeak.setText("WEAK");
        lblWeak.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(lblWeak, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 30));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 200, 10));
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 680, 630));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg.jpg"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(1360, 720));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        new CustomerLoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        //String date = ((JTextField)dateDOB.getDateEditor().getUiComponent()).getText();
        //String date2= dateDOB.getDate().toString();
        //int week= dateDOB.getCalendar().getWeeks();
        //lblDATE.setText(date2);
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyTyped
        
    }//GEN-LAST:event_txtFirstNameKeyTyped

    private void txtFirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyReleased
        // TODO add your handling code here:
        checkValueTyped(txtFirstName.getText().length(), lblOutFName, lblInFName);
    }//GEN-LAST:event_txtFirstNameKeyReleased

    private void txtFirstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyPressed
        
    }//GEN-LAST:event_txtFirstNameKeyPressed

    private void txtSurNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSurNameKeyReleased
        // TODO add your handling code here:
        checkValueTyped(txtSurName.getText().length(), lblOutSName, lblInSName);
    }//GEN-LAST:event_txtSurNameKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        checkValueTyped(txtEmail.getText().length(), lblOutEmail, lblInEmail);
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtPhoneNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumberKeyReleased
        // TODO add your handling code here:
        checkValueTyped(txtPhoneNumber.getText().length(), lblOutPhoneNumber, lblInPhoneNumber);
    }//GEN-LAST:event_txtPhoneNumberKeyReleased

    private void txtStreetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStreetKeyReleased
        // TODO add your handling code here:
        checkValueTyped(txtStreet.getText().length(), lblOutStreetName, lblInStreetName);
    }//GEN-LAST:event_txtStreetKeyReleased

    private void txtCityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyReleased
        // TODO add your handling code here:
        checkValueTyped(txtCity.getText().length(), lblOutCity, lblInCity);
    }//GEN-LAST:event_txtCityKeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        // TODO add your handling code here:
        checkValueTyped(txtPassword.getText().length(), lblOutPassword, lblInPassword);
        
        lblWeak.setVisible(true);
        lblStrong.setVisible(true);
        jProgressBar1.setVisible(true);
        int pLength = txtPassword.getText().length();
        if(pLength>0 && pLength<=3)
            jProgressBar1.setValue(20);
        else if(pLength>3 && pLength<=6)
            jProgressBar1.setValue(40);
        else if(pLength>6 && pLength<=9)
            jProgressBar1.setValue(60);
        else if(pLength>9 && pLength<=12)
            jProgressBar1.setValue(80);
        else if(pLength>12)
            jProgressBar1.setValue(100);
        else
            jProgressBar1.setValue(0);
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void txtConfirmPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmPasswordKeyReleased
        // TODO add your handling code here:
        checkValueTyped(txtConfirmPassword.getText().length(), lblOutConPassword, lblInConPassword);
        
        String p1 = txtPassword.getText();
        String p2 = txtConfirmPassword.getText();
        
        if(p2.length()>0)
        {
            panelPassword.setVisible(true);
            if(p1.equals(p2) && !txtPassword.equals("") && !txtConfirmPassword.equals(""))
                panelPassword.setBorder(BorderFactory.createLineBorder(Color.green, 2));
            else
                panelPassword.setBorder(BorderFactory.createLineBorder(Color.red, 2));
        }
    }//GEN-LAST:event_txtConfirmPasswordKeyReleased

    private void dateDOBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateDOBKeyReleased
        // TODO add your handling code here:
        checkValueTyped(dateDOB.getDate().toString().length(), lblOutDOB, lblInDOB);
    }//GEN-LAST:event_dateDOBKeyReleased

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        String fName = txtFirstName.getText();
        String lName = txtSurName.getText();
        String custEmail = txtEmail.getText(); 
        String password = txtPassword.getText();
        String confirmPassword = txtConfirmPassword.getText();
        String gender;
        if(radioMale.isSelected())
            gender = "Male" ; 
        else
            gender ="Female";
        String dob = ((JTextField)dateDOB.getDateEditor().getUiComponent()).getText(); 
        String pNumber = txtPhoneNumber.getText(); 
        String address1 = txtStreet.getText(); 
        String address2 = txtCity.getText();
        
        String msg;
        
        if(!fName.isEmpty()){
            if(!lName.isEmpty()){
                if(!custEmail.isEmpty()){
                    if(!dob.isEmpty()){
                        if(!pNumber.isEmpty()){
                            if(!address1.isEmpty()){
                                if(!address2.isEmpty()){
                                    if(!password.isEmpty()){
                                        if(password.equals(confirmPassword)){
                                            Customer customer1 = new Customer(fName,lName,custEmail,password,gender,dob,pNumber,address1,address2);
                                            msg = customer1.errorMsg;
                                            if(msg.equals("Succesfully registered")){
                                                JOptionPane.showMessageDialog(rootPane, msg, "Success Message", JOptionPane.PLAIN_MESSAGE);
                                                new CustomerLoginPage().setVisible(true);
                                                this.dispose();
                                            }
                                            else
                                                msg = msg;
                                        }
                                        else
                                        msg = "passwords doesn't match make sure you have typed same password";
                                    }
                                    else
                                        msg = "Password field is empty, mandotory feilds cannot be empty";
                                }
                                else
                                    msg = "City field is empty, mandotory feilds cannot be empty";
                            }
                            else
                                msg = "Street Address field is empty, mandotory feilds cannot be empty";
                        }
                        else
                            msg = "Phone Number field is empty, mandotory feilds cannot be empty";
                    }
                    else
                        msg = "Date Of Birth field is empty, mandotory feilds cannot be empty";
                }
                else
                    msg = "email field is empty, mandotory feilds cannot be empty";
            }
            else
                msg = "Surname Name field is empty, mandotory feilds cannot be empty";
        }
        else
            msg = "First Name field is empty, mandotory feilds cannot be empty";
        
        if(!msg.equals("Succesfully registered"))
            JOptionPane.showMessageDialog(rootPane, msg, "Error message", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void radioFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioFemaleActionPerformed

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        // TODO add your handling code here:
        int passlength = txtPassword.getPassword().length;
        
        if(passlength>=15)
        {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtPasswordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerRegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSignUp;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dateDOB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lblInCity;
    private javax.swing.JLabel lblInConPassword;
    private javax.swing.JLabel lblInDOB;
    private javax.swing.JLabel lblInEmail;
    private javax.swing.JLabel lblInFName;
    private javax.swing.JLabel lblInPassword;
    private javax.swing.JLabel lblInPhoneNumber;
    private javax.swing.JLabel lblInSName;
    private javax.swing.JLabel lblInStreetName;
    private javax.swing.JLabel lblOutCity;
    private javax.swing.JLabel lblOutConPassword;
    private javax.swing.JLabel lblOutDOB;
    private javax.swing.JLabel lblOutEmail;
    private javax.swing.JLabel lblOutFName;
    private javax.swing.JLabel lblOutPassword;
    private javax.swing.JLabel lblOutPhoneNumber;
    private javax.swing.JLabel lblOutPhoneNumber1;
    private javax.swing.JLabel lblOutSName;
    private javax.swing.JLabel lblOutStreetName;
    private javax.swing.JLabel lblStrong;
    private javax.swing.JLabel lblWeak;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JTextField txtCity;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtSurName;
    // End of variables declaration//GEN-END:variables

    private void hideOutterLabel()
    {
        lblOutFName.setVisible(false);
        lblOutSName.setVisible(false);
        lblOutEmail.setVisible(false);
        lblOutPhoneNumber.setVisible(false);
        lblOutStreetName.setVisible(false);
        lblOutCity.setVisible(false);
        lblOutPassword.setVisible(false);
        lblOutConPassword.setVisible(false);
        lblOutDOB.setVisible(false);
        panelPassword.setVisible(false);
        
        lblWeak.setVisible(false);
        lblStrong.setVisible(false);
        jProgressBar1.setVisible(false);
    }
    private void showInnerLabel()
    {
        lblInFName.setVisible(true);
        lblInSName.setVisible(true);
        lblInEmail.setVisible(true);
        lblInPhoneNumber.setVisible(true);
        lblInStreetName.setVisible(true);
        lblInCity.setVisible(true);
        lblInPassword.setVisible(true);
        lblInConPassword.setVisible(true);
        lblInDOB.setVisible(true);
    }
    
    public void checkValueTyped(int length, javax.swing.JLabel outterLabel, javax.swing.JLabel innerLabel)
    {
        if(length == 0)
        {
            
            outterLabel.setVisible(false);
            innerLabel.setVisible(true);
        }
        else
        {   
            outterLabel.setVisible(true);
            innerLabel.setVisible(false);
        }
    }

    private void reset() {
        txtCity.setText("");
        txtConfirmPassword.setText("");
        txtEmail.setText("");
        txtFirstName.setText("");
        txtPassword.setText("");
        txtPhoneNumber.setText("");
        txtStreet.setText("");
        txtSurName.setText("");
        dateDOB.setDate(null);
        radioMale.setSelected(true);
        radioFemale.setSelected(false);
        jProgressBar1.setValue(0);
        hideOutterLabel();
        showInnerLabel();
        panelPassword.setVisible(false);
    }
    
}
