/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Frames;


import Class.Employee;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Arun
 */
public class EmpDashboard extends JFrame {
    int noOfRecord=0;
    String[] selectedWeek = new String[7];
    Employee emp = new Employee();
    public static String searchString = "";
    

    /** Creates new form EmpDashboard */
    public EmpDashboard() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        panelModify.setVisible(false);
        lblUsername.setText(Employee.employeeName);
        emp.loadAllRoute(table,panelModify,panelTable,labelID,comboDeptCountry1,comboDeptTown1,comboDestCountry1,
                comboDestTown1,spinHour1,spinMinute1,spinAmPm1,txtPrice1,comboWeek);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        comboDeptTown = new javax.swing.JComboBox<>();
        comboDeptCountry = new javax.swing.JComboBox<>();
        spinMinute = new javax.swing.JSpinner();
        comboDestTown = new javax.swing.JComboBox<>();
        txtPrice = new javax.swing.JTextField();
        comboDestCountry = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        checkTuesday = new javax.swing.JCheckBox();
        checkMonday = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        checkThursday = new javax.swing.JCheckBox();
        checkWednesday = new javax.swing.JCheckBox();
        checkSaturday = new javax.swing.JCheckBox();
        checkFriday = new javax.swing.JCheckBox();
        checkSunday = new javax.swing.JCheckBox();
        btnReset = new javax.swing.JButton();
        spinHour = new javax.swing.JSpinner();
        spinAmPm = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        comboDeptCountry2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        comboDestCountry2 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        txtPrice2 = new javax.swing.JTextField();
        comboWeek1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        panelModify = new javax.swing.JPanel();
        btn = new javax.swing.JButton();
        labelID = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        comboWeek = new javax.swing.JComboBox<>();
        comboDeptCountry1 = new javax.swing.JComboBox<>();
        comboDeptTown1 = new javax.swing.JComboBox<>();
        comboDestCountry1 = new javax.swing.JComboBox<>();
        comboDestTown1 = new javax.swing.JComboBox<>();
        spinHour1 = new javax.swing.JSpinner();
        spinMinute1 = new javax.swing.JSpinner();
        spinAmPm1 = new javax.swing.JSpinner();
        txtPrice1 = new javax.swing.JTextField();
        btnModify = new javax.swing.JButton();
        btnDeleteRoute = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N

        lblUsername.setFont(new java.awt.Font("Roboto Light", 1, 20)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(129, 132, 135));
        lblUsername.setText("USERNAME");

        btnLogout.setBackground(new java.awt.Color(129, 132, 135));
        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 819, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 100));

        jPanel3.setBackground(new java.awt.Color(190, 33, 56));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ADD NEW ROUTE");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 20, 337, -1));

        btnAdd.setBackground(new java.awt.Color(204, 204, 204));
        btnAdd.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 100, 40));

        comboDeptTown.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboDeptTown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- choose town -", "Paris", "Lyon", "Strasbourg", "Madrid", "Barcelona", "Bilbao", "Berlin", "Munich", "Frankfurt" }));
        comboDeptTown.setPreferredSize(new java.awt.Dimension(180, 30));
        comboDeptTown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDeptTownActionPerformed(evt);
            }
        });
        jPanel3.add(comboDeptTown, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        comboDeptCountry.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboDeptCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- choose country -", "France", "Spain", "Germany" }));
        comboDeptCountry.setPreferredSize(new java.awt.Dimension(180, 30));
        comboDeptCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDeptCountryActionPerformed(evt);
            }
        });
        jPanel3.add(comboDeptCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        spinMinute.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spinMinute.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        spinMinute.setEditor(new javax.swing.JSpinner.NumberEditor(spinMinute, ""));
        jPanel3.add(spinMinute, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 50, 30));

        comboDestTown.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboDestTown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- choose town -", "Paris", "Lyon", "Strasbourg", "Madrid", "Barcelona", "Bilbao", "Berlin", "Munich", "Frankfurt" }));
        comboDestTown.setPreferredSize(new java.awt.Dimension(180, 30));
        jPanel3.add(comboDestTown, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        txtPrice.setPreferredSize(new java.awt.Dimension(180, 30));
        jPanel3.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        comboDestCountry.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboDestCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- choose country -", "France", "Spain", "Germany" }));
        comboDestCountry.setPreferredSize(new java.awt.Dimension(180, 30));
        comboDestCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDestCountryActionPerformed(evt);
            }
        });
        jPanel3.add(comboDestCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("DESTN - TOWN");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 140, 30));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("DEPARTURE");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 140, 30));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("DEPT - TOWN");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 140, 30));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("IN A WEEK");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 140, 30));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("DESTINATION");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 140, 30));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("DEPT - TIME");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 140, 30));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("PRICE");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 140, 30));

        checkTuesday.setForeground(new java.awt.Color(255, 255, 255));
        checkTuesday.setText("TUESDAY");
        checkTuesday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkTuesdayMouseClicked(evt);
            }
        });
        checkTuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTuesdayActionPerformed(evt);
            }
        });
        jPanel3.add(checkTuesday, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        checkMonday.setForeground(new java.awt.Color(255, 255, 255));
        checkMonday.setText("MONDAY");
        checkMonday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkMondayMouseClicked(evt);
            }
        });
        checkMonday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMondayActionPerformed(evt);
            }
        });
        jPanel3.add(checkMonday, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("AVAILABLE DAY");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 140, 30));

        checkThursday.setForeground(new java.awt.Color(255, 255, 255));
        checkThursday.setText("THURSDAY");
        checkThursday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkThursdayActionPerformed(evt);
            }
        });
        jPanel3.add(checkThursday, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, -1));

        checkWednesday.setForeground(new java.awt.Color(255, 255, 255));
        checkWednesday.setText("WEDNESDAY");
        checkWednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkWednesdayActionPerformed(evt);
            }
        });
        jPanel3.add(checkWednesday, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        checkSaturday.setForeground(new java.awt.Color(255, 255, 255));
        checkSaturday.setText("SATURDAY");
        checkSaturday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSaturdayActionPerformed(evt);
            }
        });
        jPanel3.add(checkSaturday, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, -1, -1));

        checkFriday.setForeground(new java.awt.Color(255, 255, 255));
        checkFriday.setText("FRIDAY");
        checkFriday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFridayActionPerformed(evt);
            }
        });
        jPanel3.add(checkFriday, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, -1, -1));

        checkSunday.setForeground(new java.awt.Color(255, 255, 255));
        checkSunday.setText("SUNDAY");
        checkSunday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSundayActionPerformed(evt);
            }
        });
        jPanel3.add(checkSunday, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, -1, -1));

        btnReset.setBackground(new java.awt.Color(204, 204, 255));
        btnReset.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel3.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 100, 40));

        spinHour.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spinHour.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        spinHour.setEditor(new javax.swing.JSpinner.NumberEditor(spinHour, ""));
        spinHour.setInheritsPopupMenu(true);
        jPanel3.add(spinHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 50, 30));

        spinAmPm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spinAmPm.setModel(new javax.swing.SpinnerListModel(new String[] {"AM", "PM"}));
        jPanel3.add(spinAmPm, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 50, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("MM");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 265, -1, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("HH");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 265, -1, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 360, 620));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 33, 56), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setAutoCreateRowSorter(true);
        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 33, 56), 2));
        table.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dept Country", "Dept Town", "Dest Country", "Dest Town", "Week", "Time", "Price", "Capacity", "Emp_ID", "Modify/ Delete"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.setColumnSelectionAllowed(true);
        table.setDragEnabled(true);
        table.setFillsViewportHeight(true);
        table.setGridColor(new java.awt.Color(190, 33, 56));
        table.setIntercellSpacing(new java.awt.Dimension(10, 2));
        table.setRowHeight(25);
        table.setSelectionBackground(new java.awt.Color(190, 33, 56));
        table.getTableHeader().setResizingAllowed(false);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        panelTable.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 91, 938, 479));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 33, 56), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboDeptCountry2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboDeptCountry2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- deprt country -", "France", "Spain", "Germany" }));
        comboDeptCountry2.setPreferredSize(new java.awt.Dimension(180, 30));
        comboDeptCountry2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDeptCountry2ActionPerformed(evt);
            }
        });
        jPanel5.add(comboDeptCountry2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 140, 30));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(190, 33, 56));
        jLabel14.setText("ROUTES AVAILABLE");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 13, 329, 54));

        comboDestCountry2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboDestCountry2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- dest country -", "France", "Spain", "Germany" }));
        comboDestCountry2.setPreferredSize(new java.awt.Dimension(180, 30));
        comboDestCountry2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDestCountry2ActionPerformed(evt);
            }
        });
        jPanel5.add(comboDestCountry2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 130, 30));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText(" PRICE LESS THAN ");
        jLabel24.setOpaque(true);
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 110, 20));

        txtPrice2.setPreferredSize(new java.awt.Dimension(180, 30));
        txtPrice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrice2ActionPerformed(evt);
            }
        });
        txtPrice2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrice2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrice2KeyTyped(evt);
            }
        });
        jPanel5.add(txtPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 140, -1));

        comboWeek1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboWeek1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- choose week -", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        comboWeek1.setPreferredSize(new java.awt.Dimension(180, 30));
        comboWeek1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboWeek1ActionPerformed(evt);
            }
        });
        jPanel5.add(comboWeek1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 130, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("SEARCH BY");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 13, 103, 16));

        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel5.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 130, -1));

        panelTable.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 940, 80));

        jPanel4.add(panelTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 950, 570));

        panelModify.setBackground(new java.awt.Color(255, 255, 255));
        panelModify.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 33, 56), 2));
        panelModify.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn.setText("jButton3");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        panelModify.add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, -1, -1));

        labelID.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        labelID.setForeground(new java.awt.Color(190, 33, 56));
        panelModify.add(labelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 103, 32));

        jLabel16.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(190, 33, 56));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Departure Town");
        panelModify.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 210, 32));

        jLabel17.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(190, 33, 56));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Route ID");
        panelModify.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 33, 210, 32));

        jLabel18.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(190, 33, 56));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Departure Country");
        panelModify.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 210, 32));

        jLabel19.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(190, 33, 56));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Week Available");
        panelModify.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 210, 32));

        jLabel20.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(190, 33, 56));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Destination Country");
        panelModify.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 32));

        jLabel21.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(190, 33, 56));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Destination Town");
        panelModify.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 210, 32));

        jLabel22.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(190, 33, 56));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Departure Time");
        panelModify.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 210, 32));

        jLabel23.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(190, 33, 56));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Price");
        panelModify.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 210, 32));

        comboWeek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboWeek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- choose week -", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        comboWeek.setPreferredSize(new java.awt.Dimension(180, 30));
        comboWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboWeekActionPerformed(evt);
            }
        });
        panelModify.add(comboWeek, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        comboDeptCountry1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboDeptCountry1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- choose country -", "France", "Spain", "Germany" }));
        comboDeptCountry1.setPreferredSize(new java.awt.Dimension(180, 30));
        comboDeptCountry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDeptCountry1ActionPerformed(evt);
            }
        });
        panelModify.add(comboDeptCountry1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        comboDeptTown1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboDeptTown1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- choose town -", "Paris", "Lyon", "Strasbourg", "Madrid", "Barcelona", "Bilbao", "Berlin", "Munich", "Frankfurt" }));
        comboDeptTown1.setPreferredSize(new java.awt.Dimension(180, 30));
        comboDeptTown1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDeptTown1ActionPerformed(evt);
            }
        });
        panelModify.add(comboDeptTown1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        comboDestCountry1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboDestCountry1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- choose country -", "France", "Spain", "Germany" }));
        comboDestCountry1.setPreferredSize(new java.awt.Dimension(180, 30));
        comboDestCountry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDestCountry1ActionPerformed(evt);
            }
        });
        panelModify.add(comboDestCountry1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        comboDestTown1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboDestTown1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- choose town -", "Paris", "Lyon", "Strasbourg", "Madrid", "Barcelona", "Bilbao", "Berlin", "Munich", "Frankfurt" }));
        comboDestTown1.setPreferredSize(new java.awt.Dimension(180, 30));
        panelModify.add(comboDestTown1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        spinHour1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spinHour1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        spinHour1.setEditor(new javax.swing.JSpinner.NumberEditor(spinHour1, ""));
        spinHour1.setInheritsPopupMenu(true);
        panelModify.add(spinHour1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 50, 30));

        spinMinute1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spinMinute1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        spinMinute1.setEditor(new javax.swing.JSpinner.NumberEditor(spinMinute1, ""));
        panelModify.add(spinMinute1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 50, 30));

        spinAmPm1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spinAmPm1.setModel(new javax.swing.SpinnerListModel(new String[] {"AM", "PM"}));
        panelModify.add(spinAmPm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 50, 30));

        txtPrice1.setPreferredSize(new java.awt.Dimension(180, 30));
        panelModify.add(txtPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        btnModify.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnModify.setText("MODIFY");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        panelModify.add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 110, 40));

        btnDeleteRoute.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDeleteRoute.setForeground(new java.awt.Color(205, 0, 0));
        btnDeleteRoute.setText("DELETE ROUTE");
        btnDeleteRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRouteActionPerformed(evt);
            }
        });
        panelModify.add(btnDeleteRoute, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 120, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelModify.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 110, 40));

        jPanel4.add(panelModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 490, 470));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 1000, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        panelModify.setVisible(true);
        panelTable.setVisible(false);
    }//GEN-LAST:event_btnActionPerformed

    private void checkMondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMondayActionPerformed
        // TODO add your handling code here:
        if(checkMonday.isSelected())
        {
            selectedWeek[noOfRecord] = "Monday";
            noOfRecord++;
        }
        else if(!checkMonday.isSelected())
        {
            noOfRecord--;
        }
    }//GEN-LAST:event_checkMondayActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetRoute();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String errorMsg="";
        
        String deptCountry = comboDeptCountry.getSelectedItem().toString();
        String deptTown = comboDeptTown.getSelectedItem().toString();
        String destCountry = comboDestCountry.getSelectedItem().toString();
        String destTown = comboDestTown.getSelectedItem().toString();
        String hour = spinHour.getValue().toString();
        String minute = spinMinute.getValue().toString();
        String amPM = spinAmPm.getValue().toString();
        String deptTime = hour + ":" + minute + " " + amPM;
        double price=0;
        try {
            price = Double.parseDouble((txtPrice.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Price field accept only number, Please check your value", "Incorrect Input", 
                    JOptionPane.ERROR_MESSAGE);
        }

//        for(int j=0;j<noOfRecord;j++)
//        {
//            System.out.println(selectedWeek[j]+"\n");
//        }
        if(!(comboDeptCountry.getSelectedIndex()==0))
        {
            if(!(comboDeptTown.getSelectedIndex()==0))
            {
                if(!(comboDestCountry.getSelectedIndex()==0))
                {
                    if(!(comboDestTown.getSelectedIndex()==0))
                    {
                        if(!(noOfRecord==0))
                        {
                            for(int i=0;i<noOfRecord;i++)
                            {
                                errorMsg = emp.addRoute(deptCountry, deptTown, destCountry, destTown, deptTime, price, selectedWeek[i]);
                                resetRoute();
                                emp.loadAllRoute(table,panelModify,panelTable,labelID,comboDeptCountry1,comboDeptTown1,comboDestCountry1,
                                comboDestTown1,spinHour1,spinMinute1,spinAmPm1,txtPrice1,comboWeek);
                            }
                            if(errorMsg=="Succesfully added")
                                    JOptionPane.showMessageDialog(rootPane, errorMsg, noOfRecord+" Route added successfully", JOptionPane.PLAIN_MESSAGE);
                        }
                        else
                            errorMsg="Invalid selection, Please select weeks on the route operates";
                    }
                    else
                        errorMsg="Invalid selection, Please select a destination town";
                }
                else
                    errorMsg="Invalid selection, Please select a destination country";
            }
            else
                errorMsg="Invalid selection, Please select a departure town";
        }
        else
            errorMsg="Invalid selection, Please select a departure country";
        if((errorMsg!="")&&(errorMsg!="Succesfully added"))
            JOptionPane.showMessageDialog(rootPane, errorMsg, "Invalid Selection", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void checkTuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTuesdayActionPerformed
        // TODO add your handling code here:
        if(checkTuesday.isSelected())
        {
            selectedWeek[noOfRecord] = "Tuesday";
            noOfRecord++;
        }
        else if(!checkTuesday.isSelected())
        {
            noOfRecord--;
        }
    }//GEN-LAST:event_checkTuesdayActionPerformed

    private void checkMondayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMondayMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_checkMondayMouseClicked

    private void checkTuesdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkTuesdayMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_checkTuesdayMouseClicked

    private void checkWednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkWednesdayActionPerformed
        // TODO add your handling code here:
        if(checkWednesday.isSelected())
        {
            selectedWeek[noOfRecord] = "Wednesday";
            noOfRecord++;
        }
        else if(!checkWednesday.isSelected())
        {
            noOfRecord--;
        }
    }//GEN-LAST:event_checkWednesdayActionPerformed

    private void checkThursdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkThursdayActionPerformed
        // TODO add your handling code here:
        if(checkThursday.isSelected())
        {
            selectedWeek[noOfRecord] = "Thursday";
            noOfRecord++;
        }
        else if(!checkThursday.isSelected())
        {
            noOfRecord--;
        }
    }//GEN-LAST:event_checkThursdayActionPerformed

    private void checkFridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFridayActionPerformed
        // TODO add your handling code here:
        if(checkFriday.isSelected())
        {
            selectedWeek[noOfRecord] = "Friday";
            noOfRecord++;
        }
        else if(!checkFriday.isSelected())
        {
            noOfRecord--;
        }
    }//GEN-LAST:event_checkFridayActionPerformed

    private void checkSaturdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSaturdayActionPerformed
        // TODO add your handling code here:
        if(checkSaturday.isSelected())
        {
            selectedWeek[noOfRecord] = "Saturday";
            noOfRecord++;
        }
        else if(!checkSaturday.isSelected())
        {
            noOfRecord--;
        }
    }//GEN-LAST:event_checkSaturdayActionPerformed

    private void checkSundayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSundayActionPerformed
        // TODO add your handling code here:
        if(checkSunday.isSelected())
        {
            selectedWeek[noOfRecord] = "Sunday";
            noOfRecord++;
        }
        else if(!checkSunday.isSelected())
        {
            noOfRecord--;
        }
    }//GEN-LAST:event_checkSundayActionPerformed

    private void comboDeptTownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDeptTownActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboDeptTownActionPerformed

    private void comboDeptCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDeptCountryActionPerformed
        // TODO add your handling code here:
        if(comboDeptCountry.getSelectedIndex()==1)
        {
            comboDeptTown.removeAllItems();
            comboDeptTown.addItem(" -choose town- ");
            comboDeptTown.addItem("Paris");
            comboDeptTown.addItem("Lyon");
            comboDeptTown.addItem("Strasbourg");
            comboDestCountry.removeAllItems();
            comboDestCountry.addItem(" -choose country- ");
            comboDestCountry.addItem("Spain");
            comboDestCountry.addItem("Germany");
            comboDestTown.removeAllItems();
            comboDestTown.addItem(" -choose town- ");
        }
        else if(comboDeptCountry.getSelectedIndex()==2)
        {
            comboDeptTown.removeAllItems();
            comboDeptTown.addItem(" -choose town- ");
            comboDeptTown.addItem("Madrid");
            comboDeptTown.addItem("Barcelona");
            comboDeptTown.addItem("Bilbao");
            comboDestCountry.removeAllItems();
            comboDestCountry.addItem(" -choose country- ");
            comboDestCountry.addItem("Germany");
            comboDestCountry.addItem("France");
            comboDestTown.removeAllItems();
            comboDestTown.addItem(" -choose town- ");
        }
        else if(comboDeptCountry.getSelectedIndex()==3)
        {
            comboDeptTown.removeAllItems();
            comboDeptTown.addItem(" -choose town- ");
            comboDeptTown.addItem("Berlin");
            comboDeptTown.addItem("Munich");
            comboDeptTown.addItem("Frankfurt");
            comboDestCountry.removeAllItems();
            comboDestCountry.addItem(" -choose country- ");
            comboDestCountry.addItem("Spain");
            comboDestCountry.addItem("France");
            comboDestTown.removeAllItems();
            comboDestTown.addItem(" -choose town- ");
        }
    }//GEN-LAST:event_comboDeptCountryActionPerformed

    private void comboDestCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDestCountryActionPerformed
        // TODO add your handling code here:
        if(comboDestCountry.getSelectedItem()=="France")
        {
            comboDestTown.removeAllItems();
            comboDestTown.addItem(" -choose town- ");
            comboDestTown.addItem("Paris");
            comboDestTown.addItem("Lyon");
            comboDestTown.addItem("Strasbourg");
        }
        else if(comboDestCountry.getSelectedItem()=="Spain")
        {
            comboDestTown.removeAllItems();
            comboDestTown.addItem(" -choose town- ");
            comboDestTown.addItem("Madrid");
            comboDestTown.addItem("Barcelona");
            comboDestTown.addItem("Bilbao");
        }
        else if(comboDestCountry.getSelectedItem()=="Germany")
        {
            comboDestTown.removeAllItems();
            comboDestTown.addItem(" -choose town- ");
            comboDestTown.addItem("Berlin");
            comboDestTown.addItem("Munich");
            comboDestTown.addItem("Frankfurt");
        }
    }//GEN-LAST:event_comboDestCountryActionPerformed

    private void comboDeptCountry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDeptCountry1ActionPerformed
        // TODO add your handling code here:
        if(comboDeptCountry1.getSelectedIndex()==1)
        {
            comboDeptTown1.removeAllItems();
            comboDeptTown1.addItem(" -choose town- ");
            comboDeptTown1.addItem("Paris");
            comboDeptTown1.addItem("Lyon");
            comboDeptTown1.addItem("Strasbourg");
            comboDestCountry1.removeAllItems();
            comboDestCountry1.addItem(" -choose country- ");
            comboDestCountry1.addItem("Spain");
            comboDestCountry1.addItem("Germany");
            comboDestTown1.removeAllItems();
            comboDestTown1.addItem(" -choose town- ");
        }
        else if(comboDeptCountry1.getSelectedIndex()==2)
        {
            comboDeptTown1.removeAllItems();
            comboDeptTown1.addItem(" -choose town- ");
            comboDeptTown1.addItem("Madrid");
            comboDeptTown1.addItem("Barcelona");
            comboDeptTown1.addItem("Bilbao");
            comboDestCountry1.removeAllItems();
            comboDestCountry1.addItem(" -choose country- ");
            comboDestCountry1.addItem("Germany");
            comboDestCountry1.addItem("France");
            comboDestTown1.removeAllItems();
            comboDestTown1.addItem(" -choose town- ");
        }
        else if(comboDeptCountry1.getSelectedIndex()==3)
        {
            comboDeptTown1.removeAllItems();
            comboDeptTown1.addItem(" -choose town- ");
            comboDeptTown1.addItem("Berlin");
            comboDeptTown1.addItem("Munich");
            comboDeptTown1.addItem("Frankfurt");
            comboDestCountry1.removeAllItems();
            comboDestCountry1.addItem(" -choose country- ");
            comboDestCountry1.addItem("Spain");
            comboDestCountry1.addItem("France");
            comboDestTown1.removeAllItems();
            comboDestTown1.addItem(" -choose town- ");
        }
    }//GEN-LAST:event_comboDeptCountry1ActionPerformed

    private void comboDeptTown1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDeptTown1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDeptTown1ActionPerformed

    private void comboDestCountry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDestCountry1ActionPerformed
        // TODO add your handling code here:
        if(comboDestCountry1.getSelectedItem()=="France")
        {
            comboDestTown1.removeAllItems();
            comboDestTown1.addItem(" -choose town- ");
            comboDestTown1.addItem("Paris");
            comboDestTown1.addItem("Lyon");
            comboDestTown1.addItem("Strasbourg");
        }
        else if(comboDestCountry1.getSelectedItem()=="Spain")
        {
            comboDestTown1.removeAllItems();
            comboDestTown1.addItem(" -choose town- ");
            comboDestTown1.addItem("Madrid");
            comboDestTown1.addItem("Barcelona");
            comboDestTown1.addItem("Bilbao");
        }
        else if(comboDestCountry1.getSelectedItem()=="Germany")
        {
            comboDestTown1.removeAllItems();
            comboDestTown1.addItem(" -choose town- ");
            comboDestTown1.addItem("Berlin");
            comboDestTown1.addItem("Munich");
            comboDestTown1.addItem("Frankfurt");
        }
    }//GEN-LAST:event_comboDestCountry1ActionPerformed

    private void comboWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboWeekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboWeekActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
        int Id= Integer.parseInt(labelID.getText());
        String deptCountry = comboDeptCountry1.getSelectedItem().toString();
        String deptTown = comboDeptTown1.getSelectedItem().toString();
        String destCountry = comboDestCountry1.getSelectedItem().toString();
        String destTown = comboDestTown1.getSelectedItem().toString();
            String hour = spinHour1.getValue().toString();
            String minute = spinMinute1.getValue().toString();
            String am = spinAmPm1.getValue().toString();
        String time = hour + ":" + minute + " " + am;
        double price=0;
        try {
            price = Double.parseDouble((txtPrice1.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Price field accept only number, Please check your value", "Incorrect Input", 
                    JOptionPane.ERROR_MESSAGE);
        }
        String week = comboWeek.getSelectedItem().toString();
        
        if(!(comboDeptCountry1.getSelectedIndex()==0))
        {
            if(!(comboDeptTown1.getSelectedIndex()==0))
            {
                if(!(comboDestCountry1.getSelectedIndex()==0))
                {
                    if(!(comboDestTown1.getSelectedIndex()==0))
                    {   
                        int code;
                        
                        code = emp.modifyRoute(Id, deptCountry, deptTown, destCountry, destTown, time, price, week);
                        
                        if(code>0)
                        {
                            JOptionPane.showMessageDialog(rootPane, "Record modification successfull", "Updated Successfully", JOptionPane.INFORMATION_MESSAGE);
                            panelModify.setVisible(false);
                            emp.loadAllRoute(table,panelModify,panelTable,labelID,comboDeptCountry1,comboDeptTown1,comboDestCountry1,
                                comboDestTown1,spinHour1,spinMinute1,spinAmPm1,txtPrice1,comboWeek);
                            panelTable.setVisible(true);
                        }
                        else
                            JOptionPane.showMessageDialog(rootPane, "Record modification failed", "Update Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnDeleteRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRouteActionPerformed
        // TODO add your handling code here:
        
            int Id= Integer.parseInt(labelID.getText());
        int code = emp.deleteRoute(Id);
        if(code>0)
        {
            JOptionPane.showMessageDialog(rootPane, "record Successful deleted", "Deleting Successful", JOptionPane.INFORMATION_MESSAGE);
            panelModify.setVisible(false);
            emp.loadAllRoute(table,panelModify,panelTable,labelID,comboDeptCountry1,comboDeptTown1,comboDestCountry1,
                comboDestTown1,spinHour1,spinMinute1,spinAmPm1,txtPrice1,comboWeek);
            panelTable.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Deleting record failed", "Deleting error", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_btnDeleteRouteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panelModify.setVisible(false);
        panelTable.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboDeptCountry2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDeptCountry2ActionPerformed
        // TODO add your handling code here:
        switch (comboDeptCountry2.getSelectedIndex()) {
            case 1:
                comboDestCountry2.removeAllItems();
                comboDestCountry2.addItem(" -dest country- ");
                comboDestCountry2.addItem("Spain");
                comboDestCountry2.addItem("Germany");
                break;
            case 2:
                comboDestCountry2.removeAllItems();
                comboDestCountry2.addItem(" -dest country- ");
                comboDestCountry2.addItem("Germany");
                comboDestCountry2.addItem("France");
                break;
            case 3:
                comboDestCountry2.removeAllItems();
                comboDestCountry2.addItem(" -dest country- ");
                comboDestCountry2.addItem("Spain");
                comboDestCountry2.addItem("France");
                break;
            default:
                break;
        }
        if(comboDeptCountry2.getSelectedIndex()>0)
        {
            if(searchString.length()>0)
                searchString = searchString + " AND departure_Country='"+comboDeptCountry2.getSelectedItem().toString()+"'";
            else
                searchString = searchString + " where departure_Country='"+comboDeptCountry2.getSelectedItem().toString()+"'";
        }
        
    }//GEN-LAST:event_comboDeptCountry2ActionPerformed

    private void comboDestCountry2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDestCountry2ActionPerformed
        // TODO add your handling code here:
        if(comboDestCountry2.getSelectedIndex()>0)
        {
            if(searchString.length()>0)
                searchString = searchString + " AND destination_Country='"+comboDestCountry2.getSelectedItem().toString()+"'";
            else
                searchString = searchString + " where destination_Country='"+comboDestCountry2.getSelectedItem().toString()+"'";
        }
    }//GEN-LAST:event_comboDestCountry2ActionPerformed

    private void comboWeek1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboWeek1ActionPerformed
        // TODO add your handling code here:
        if(comboWeek1.getSelectedIndex()>0)
        {
            if(searchString.length()>0)
                searchString = searchString + " AND week='"+comboWeek1.getSelectedItem().toString()+"'";
            else
                searchString = searchString + " where week='"+comboWeek1.getSelectedItem().toString()+"'";
        }
    }//GEN-LAST:event_comboWeek1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if(txtPrice2.getText().length()>0)
        {
            try{
                if(searchString.length()>0)
                    searchString = searchString + " AND price<="+Double.parseDouble(txtPrice2.getText());
                else
                    searchString = searchString + " where price<="+Double.parseDouble(txtPrice2.getText());
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(rootPane, "Price field accept only number, Please check your value", "Incorrect Input", 
                        JOptionPane.ERROR_MESSAGE);
            }
            emp.loadAllRoute(table,panelModify,panelTable,labelID,comboDeptCountry1,comboDeptTown1,comboDestCountry1,
                    comboDestTown1,spinHour1,spinMinute1,spinAmPm1,txtPrice1,comboWeek);
        }
        else
        {
            emp.loadAllRoute(table,panelModify,panelTable,labelID,comboDeptCountry1,comboDeptTown1,comboDestCountry1,
                    comboDestTown1,spinHour1,spinMinute1,spinAmPm1,txtPrice1,comboWeek);
        }
        searchString="";
        comboDeptCountry2.setSelectedIndex(0);
        comboDestCountry2.removeAllItems();
        comboDestCountry2.addItem(" -dest country- ");
        comboDestCountry2.setSelectedIndex(0);
        comboDestCountry2.addItem("France");
        comboDestCountry2.addItem("Germany");
        comboDestCountry2.addItem("spain");
        txtPrice2.setText("");
        comboWeek1.setSelectedIndex(0);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtPrice2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrice2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrice2KeyTyped

    private void txtPrice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrice2ActionPerformed

    private void txtPrice2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrice2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrice2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDeleteRoute;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox checkFriday;
    private javax.swing.JCheckBox checkMonday;
    private javax.swing.JCheckBox checkSaturday;
    private javax.swing.JCheckBox checkSunday;
    private javax.swing.JCheckBox checkThursday;
    private javax.swing.JCheckBox checkTuesday;
    private javax.swing.JCheckBox checkWednesday;
    private javax.swing.JComboBox<String> comboDeptCountry;
    private javax.swing.JComboBox<String> comboDeptCountry1;
    private javax.swing.JComboBox<String> comboDeptCountry2;
    private javax.swing.JComboBox<String> comboDeptTown;
    private javax.swing.JComboBox<String> comboDeptTown1;
    private javax.swing.JComboBox<String> comboDestCountry;
    private javax.swing.JComboBox<String> comboDestCountry1;
    private javax.swing.JComboBox<String> comboDestCountry2;
    private javax.swing.JComboBox<String> comboDestTown;
    private javax.swing.JComboBox<String> comboDestTown1;
    private javax.swing.JComboBox<String> comboWeek;
    private javax.swing.JComboBox<String> comboWeek1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel panelModify;
    private javax.swing.JPanel panelTable;
    private javax.swing.JSpinner spinAmPm;
    private javax.swing.JSpinner spinAmPm1;
    private javax.swing.JSpinner spinHour;
    private javax.swing.JSpinner spinHour1;
    private javax.swing.JSpinner spinMinute;
    private javax.swing.JSpinner spinMinute1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtPrice1;
    private javax.swing.JTextField txtPrice2;
    // End of variables declaration//GEN-END:variables

    private void resetRoute() {
        comboDeptCountry.setSelectedIndex(0);
        comboDeptTown.setSelectedIndex(0);
        comboDestCountry.setSelectedIndex(0);
        comboDestTown.setSelectedIndex(0);
        spinHour.setValue(1);
        spinMinute.setValue(0);
        spinAmPm.setValue("AM");
        txtPrice.setText("");
        checkMonday.setSelected(false);
        checkTuesday.setSelected(false);
        checkWednesday.setSelected(false);
        checkThursday.setSelected(false);
        checkFriday.setSelected(false);
        checkSaturday.setSelected(false);
        checkSunday.setSelected(false);
    }

}
